### ISSUE TITLE
thank you for this work

### ISSUE THREAD

**Issue by Muhammed-Hayr-Ali** [RaajeevChandran/Firebase-in-Flutter-with-Provider-Medium#1]
I would like to thank you for this work
  Can you improve this business for more benefit?
Add a one-time display introduction
And add a splash screen

**Comment by RaajeevChandran** [comment]
Hey there! Glad that my repository turned out to be helpful to you. Since I created this repository in addition to my Medium article, I intended to keep it dead-simple. So, I'll try to add this in the days to come. Thanks.

**Comment by RaajeevChandran** [comment]
Hey there! Glad that my repository turned out to be helpful to you. Since I created this repository in addition to my Medium article, I intended to keep it dead-simple. So, I'll try to add this in the days to come. Thanks.
